runtime: python37
#[END gae_flex_mysql_settings]
env_variables:
  #dialect+driver://username:password@host:port/database
  #SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://alvarov:lata5comprar@/prueba_appengine?unix_socket:/cloudsql/asistente-180018:southamerica-east1:bd-bsa-chequeo-planta'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://alvarov:lata5comprar@127.0.0.1:3306/prueba_appengine'

  CLOUD_SQL_CONNECTION_NAME: 'asistente-180018:southamerica-east1:bd-bsa-chequeo-planta'
  DB_USER: 'alvarov'
  DB_PASS: 'lata5comprar'
  DB_NAME: 'prueba_appengine'